title: Carlos Quintos Nores
logo: /assets/img/logo.jpg
email: 90f0ad@gmail.com
lang: en-US
description: Technician in Networked Computer Systems Administration / CFPM IC10 / IFC361_1
favicon: true
color-scheme: auto
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

platforms:
  - name: Resume
    icon: <i class="fa-solid fa-file-lines"></i>
    link: /assets/files/CV-CarlosQuintos.pdf
  - name: Github
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/cequintos/

navigation:
  - name: About Me
    link: ./index.html
  - name: Work Experience
    link: ./work_experencie.html
  - name: Education and Training
    link: ./education_and_training.html
  - name: Skills
    link: ./skills.html